name: image-pipeline
path: modules/analysis/rosbag-image-pipeline
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: source-bucket
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: RawBucketName
  - name: intermediate-bucket
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: IntermediateBucketName
  - name: dag-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: ArtifactsBucketName
  - name: dag-path
    valueFrom:
      moduleMetadata:
        group: core
        name: mwaa
        key: DagPath
  - name: full-access-policy-arn
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: FullAccessPolicyArn
  - name: on-demand-job-queue-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: batch-compute
        key: OnDemandJobQueueArn
  - name: spot-job-queue-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: batch-compute
        key: SpotJobQueueArn
  - name: fargate-job-queue-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: batch-compute
        key: FargateJobQueueArn
  - name: mwaa-exec-role
    valueFrom:
      moduleMetadata:
        group: core
        name: mwaa
        key: MwaaExecRoleArn
---
name: rosbag-scene-detection
path: "modules/analysis/rosbag-scene-detection/"
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: source-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: RawBucketName
  - name: destination-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: IntermediateBucketName
  - name: artifact-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: ArtifactsBucketName
  - name: logs-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: LogsBucketName
  - name: glue-db-name
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: GlueDBName
  - name: rosbag-bagfile-table
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagBagFileTable
  - name: rosbag-scene-metadata-table
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagSceneMetadataTable
  - name: emr
    value:
      CLUSTER_NAME: emr-compute
      MASTER_INSTANCE_TYPE: m5.xlarge
      CORE_INSTANCE_TYPE: m5.4xlarge
      CORE_INSTANCE_COUNT: 3
      CORE_INSTANCE_MARKET: ON_DEMAND
      TASK_INSTANCE_TYPE: m5.4xlarge
      TASK_INSTANCE_COUNT: 1
      TASK_INSTANCE_MARKET: SPOT
      RELEASE_LABEL: emr-6.2.0
      APPLICATIONS:
      - Hadoop
      - Spark
      CONFIGURATION:
      - Classification: spark
        Properties:
          maximizeResourceAllocation: 'true'
  - name: fargate
    value:
      image-name: ros-image
      ecr-repository-name: ros-topic-extraction
      cpu: 4096
      memory-limit-mib: 30720
      timeout-minutes: 30
  - name: rosbag-files-input-path-relative-to-s3
    value: "rosbag-scene-detection"
  - name: retention-type
    value: destroy
---
name: rosbag-webviz
path: "modules/demo-only/rosbag-webviz"
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: raw-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: RawBucketName
  - name: target-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: IntermediateBucketName
  - name: logs-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: LogsBucketName
  - name: scene-metadata-table-name
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagSceneMetadataTable
  - name: scene-metadata-partition-key
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagSceneMetadataPartitionKey
  - name: scene-metadata-sort-key
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagSceneMetadataSortKey
